#!/bin/sh

# if PROJECT_DIR is empty and there is one parameter, set it to that parameter
if [[ -z "$PROJECT_DIR" ]] && [[ $# -eq 1 ]] 
then
    export PROJECT_DIR=$1
else 
	if [[ -z "$PROJECT_DIR" ]] 
    then 
		echo "error: PROJECT_DIR is not defined. Define it or pass it as first parameter."
        exit 1
    fi
fi

# exit if the command is not in the path
if ! command -v swiftformat > /dev/null; then
  echo "error: Swiftformat is not installed. Run: brew install swiftformat"
  exit 1
fi

swiftformat ${PROJECT_DIR} --config ${PROJECT_DIR}/.swiftformat 
