let tasks_json = """
{
    "STATUS": "OK",
    "todo-items": [
        {
            "id": 18320956,
            "boardColumn": {
                "id": 64996,
                "name": "To do",
                "color": "#E74C3C"
            },
            "canComplete": true,
            "comments-count": 0,
            "description": "Cook a pie and eat it.",
            "has-reminders": false,
            "has-unread-comments": false,
            "private": 0,
            "content": "Eat pie",
            "order": 2000,
            "project-id": 468919,
            "project-name": "Costa Rica 4k",
            "todo-list-id": 1664149,
            "todo-list-name": "Cards",
            "tasklist-private": false,
            "tasklist-isTemplate": false,
            "status": "new",
            "company-name": "Beforeigners",
            "company-id": 150787,
            "creator-id": 471466,
            "creator-firstname": "Alejandro",
            "creator-lastname": "Ramirez",
            "updater-id": 0,
            "updater-firstname": "",
            "updater-lastname": "",
            "completed": false,
            "start-date": "",
            "due-date-base": "",
            "due-date": "",
            "created-on": "2019-11-24T00:23:27Z",
            "last-changed-on": "2019-11-24T00:37:06Z",
            "position": 2000,
            "estimated-minutes": 0,
            "priority": "",
            "progress": 0,
            "harvest-enabled": false,
            "parentTaskId": "",
            "lockdownId": "",
            "tasklist-lockdownId": "",
            "has-dependencies": 0,
            "has-predecessors": 0,
            "hasTickets": false,
            "timeIsLogged": "0",
            "attachments-count": 0,
            "predecessors": [],
            "canEdit": true,
            "viewEstimatedTime": true,
            "creator-avatar-url": "https://s3-eu-west-1.amazonaws.com/tw-eu-files/588434/userAvatar/twia_fd233d46c8c9c58722aa81a3b0885849.png",
            "canLogTime": true,
            "userFollowingComments": false,
            "userFollowingChanges": false,
            "DLM": 0
        }
    ]
}
"""
